services:
  paylinkdb:
    image: bitnami/postgresql:14
    container_name: paylinkdb
    environment:
      POSTGRESQL_DATABASE: ${POSTGRES_DB}
      POSTGRESQL_USERNAME: ${POSTGRES_USER}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/bitnami/postgresql
    ports:
      - 5432:5432

volumes:
  postgres:
